# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json ./

# Install dependencies (ignore scripts to skip prepare, then explicitly build)
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the project
RUN npm run build

# Expose whatever port if needed (MCP runs over stdio so nothing needed)

# Run the server
CMD ["node", "build/index.js"]
